name: Run Docker Build Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for Docker test images"
        required: true
        default: manual-test
        type: string
  push:
    branches:
      - LPAL-2194-shared-webops-actions-consolidate-docker-build-actions-with-snyk-scanning-across-teams-and-standardise-steps

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  docker_build_test:
    uses: ./.github/workflows/docker_build_test.yml
    with:
      tag: ${{ inputs.tag }}
      oidc_docker_role: ${{ vars.OIDC_DOCKER_ROLE }}
    secrets:
      SNYK_OPG_ORG_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
